Update Apprunner

diff --git a/Devops-Notes/Production-deployment-ways/Apprunner b/Devops-Notes/Production-deployment-ways/Apprunner
--- a/Devops-Notes/Production-deployment-ways/Apprunner
+++ b/Devops-Notes/Production-deployment-ways/Apprunner
@@ -1,1 +1,238 @@
 # Deploy the application in APP runner service
+-> First i setup the Ec2, VPC and ECR infrastructure in aws using terraform (https://github.com/manoj7894/Frissly-Deployment-Custom-VPC.git)
+-> I have install all the tools like jenkins, Trivy, awscli and sonarqube while i setting up the infrastructure.
+-> I will access the jenkins and sonar-qube over the web browser after i setup infrastructure.
+-> I have to setup the jenkins configuration for execute CI/CD pipeline
+
+
+-> You have to install the below plugins
+    -> EclipseTemurin
+    -> Docker
+    -> Docker pipeline
+    -> SonarQube scanner
+    -> SonarQube Quality gate
+    -> Quality gate
+    -> Nodejs
+    -> OWASP Dependency-Check
+    -> Email-extension plugin
+    -> AWS Steps
+    -> AWS Credentials
+    -> Bitbucket
+
+-> You will restart the Jenkins after install the plugins
+-> Go to manage Jenkins, click credentials and cofigure below credentials
+    docker -> Click username and password, Give username and password and give id name
+    Sonarube -> Click secret, Give token which you created in sonarqube and give id name
+    Git -> Click username and password, give username and token which you created in github, give id name
+    Email -> Click username and password, Give mail-id and email token [To get this email-token you have to go gmail, click manage google account
+                  click security and search App password in search bar and click app password and give one name and create
+    AWS-> Click AwS, Give access key and secret key
+
+-> Go to manage Jenkins, click configuration tools and install below tools
+   JDK-17, Click automatically install, Click Install from adoptium.net and choose latest version
+   JDK-11, Click automatically install, Click Install from adoptium.net and choose latest version
+   Git, Keep it default
+   Sonar-scanner, Click install automatically, Choose latest version
+   Nodejs, Give name, Click install automatically
+   Dependency check click install automatically and click Install from github.com and choose latest version
+   Maven, Give name, Click install automatically and choose latest version 
+   Docker, Give name Click install automatically and choose latest version
+
+-> After complete to configure the tools later click the system configuration
+   SonarQube-Installition, Give name, Give the Sonar-qube URL and choose the soanr-token credentials id which you have created in credentials
+   Extended Email Notification -> Give smtp.gmail.com, Give 465 port, Click Advanced choose mail-id which you created in credentals, Click use SSL
+   Email Notification -> Give smtp.gmail.com, click advanced, Give mail and email token which you created before in gmail.
+
+-> To set up the sonar-quality gate. Go to sonarqube, click administation, click configuration, click webhook and give jenkins URL 
+       http://54.198.209.63:8080/sonarqube-webhook
+
+
+pipeline {
+    agent any
+
+    tools {
+        nodejs 'node22'
+    }
+
+    environment {
+        DOCKER_IMAGE = "swigy"
+        SCANNER_HOME = tool 'sonar-scanner'
+        AWS_REGION = 'us-east-1'  // Update your AWS region
+        AWS_ACCOUNT_ID = '869935101375'
+        ECR_REPOSITORY = 'frissly'
+    }
+
+    stages {
+        stage('Remove All Previous Docker Images') {
+            steps {
+                sh 'docker rmi -f $(docker images -a -q) || true'
+            }
+        }
+
+        stage('Cleanup Old Trivy Reports') {
+            steps {
+                script {
+                    echo "Cleaning up old Trivy reports..."
+                    sh '''
+                        rm -f trivy.txt
+                        rm -f fs-report.html
+                    '''
+                }
+            }
+        }
+
+        stage('Get Code') {
+            steps {
+                git branch: 'main', credentialsId: 'Github_id', url: 'https://github.com/manoj7894/swiggy-nodejs-devops-project.git'
+            }
+        }
+
+        stage('Install Package Dependencies') {
+            steps {
+                sh "npm install"
+            }
+        }
+
+        stage('Check for Tests') {
+            steps {
+                script {
+                    def testScriptExists = sh(script: "grep -q '\"test\":' package.json", returnStatus: true) == 0
+                    env.TEST_SCRIPT_EXISTS = testScriptExists ? 'true' : 'false'
+                }
+            }
+        }
+
+        stage('Trivy Filesystem Scan') {
+            steps {
+                script {
+                    sh "trivy fs --format table -o fs-report.html ."
+                }
+            }
+        }
+
+        stage('OWASP Scan') {
+            when {
+                expression {
+                    fileExists('package.json')
+                }
+            }
+            steps {
+                dependencyCheck additionalArguments: '', odcInstallation: 'DP-Check'
+                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
+            }
+        }
+
+        stage('SonarQube') {
+            steps {
+                withSonarQubeEnv('Sonar_Install') {
+                    sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Validate \
+                    -Dsonar.projectKey=Validate \
+                    -Dsonar.host.url=http://54.173.242.65:9000'''
+                }
+            }
+        }
+
+        stage('Stage V: QualityGates') {
+            steps {
+                echo "Running Quality Gates to verify the code quality"
+                script {
+                    timeout(time: 2, unit: 'MINUTES') {
+                        def qg = waitForQualityGate()
+                        if (qg.status != 'OK') {
+                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                script {
+                    withDockerRegistry(credentialsId: 'Docker_id', toolName: 'Docker') {
+                        // Ensure image is tagged with the ECR URL and build number
+                        sh "docker build -t ${DOCKER_IMAGE} ."
+                    }
+                }
+            }
+        }
+        
+        stage('Trivy Image Scan') {
+            steps {
+                script {
+                    sh "trivy image ${DOCKER_IMAGE} > trivy.txt"
+                }
+            }
+        }
+
+        stage('Create ECR Repository if Not Exists') {
+            steps {
+                script {
+                    sh '''
+                        # Check if the repository exists, if not, create it
+                        aws ecr describe-repositories --repository-names ${ECR_REPOSITORY} --region ${AWS_REGION} || \
+                        aws ecr create-repository --repository-name ${ECR_REPOSITORY} --region ${AWS_REGION}
+                    '''
+                }
+            }
+        }
+
+        stage('Push Into ECR') {
+            steps {
+                script {
+                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS_Credetilas_id']]) {
+                        sh '''
+                            # Login to AWS ECR
+                            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+                            
+                            # Check if the image exists locally
+                            docker images | grep ${DOCKER_IMAGE}
+                            
+                            # Tag the Docker image with the correct ECR repository
+                            docker tag ${DOCKER_IMAGE} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
+                            
+                            # Push the Docker image to ECR
+                            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
+                        '''
+                    }
+                }
+            }
+        }
+    }
+
+    post {
+        always {
+            script {
+                def jobName = 'Frissly'
+                def buildNumber = env.BUILD_NUMBER
+                def pipelineStatus = currentBuild.result ?: 'UNKNOWN'
+                def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'
+
+                def body = """<html>
+                                <body>
+                                    <div style="border: 4px solid ${bannerColor}; padding: 10px;">
+                                        <h2>${jobName} - Build ${buildNumber}</h2>
+                                        <div style="background-color: ${bannerColor}; padding: 10px;">
+                                            <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
+                                        </div>
+                                        <p>Check the <a href="${BUILD_URL}">console output</a>.</p> 
+                                    </div>
+                                </body>
+                            </html>"""
+
+                emailext(
+                    subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
+                    body: body,
+                    to: 'manojvarmapotthutri@gmail.com',
+                    from: 'jenkins@example.com',
+                    replyTo: 'jenkins@example.com',
+                    attachmentsPattern: '**/fs-report.html,**/trivy.txt',
+                    mimeType: 'text/html'
+                )
+            }
+        }
+    }
+}
+
+-> After executing the above pipeline script.
+-> You will create apprunner with terraform (https://github.com/manoj7894/Frissly-Deployment-Custom-VPC.git)
