Update Infrastructure-Setup

diff --git a/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup b/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup
--- a/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup
+++ b/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup
@@ -385,3 +385,299 @@ pipeline {
 
 -> we should apply ingress after above pipeline
 -> kubectl apply -f ingress.yml -n frissly
+
+
+
+# Github Repository Pipeline Script
+
+pipeline {
+    agent any
+
+    tools {
+        nodejs 'node22'
+    }
+
+    environment {
+        DOCKER_IMAGE = "manoj3003/swigy:${BUILD_NUMBER}"
+        GIT_REPO_NAME = "swiggy-nodejs-devops-project"
+        GIT_USERNAME = "manoj7894"
+        BRANCH = "main"
+        DEPLOYMENT_FILE_PATH = "Kubernetes/deployment.yml"
+        SCANNER_HOME = tool 'sonar-scanner'
+    }
+
+    stages {
+
+        stage('Cleanup Workspace') {
+            steps {
+                script {
+                    echo "Cleaning up the workspace..."
+                    cleanWs()
+                }
+            }
+        }
+
+        stage('Remove All Previous Docker Images and Containers') {
+            steps {
+                sh 'docker rmi -f $(docker images -a -q) || true'
+                sh 'docker volume prune -f || true'
+                sh 'docker builder prune -f || true'
+                sh 'docker network prune -f || true'
+            }
+        }
+
+        stage('Cleanup Old Trivy Reports') {
+            steps {
+                sh '''
+                    rm -f trivy.txt
+                    rm -f fs-report.html
+                '''
+            }
+        }
+
+        stage('Get Code') {
+            steps {
+                git branch: "${BRANCH}", credentialsId: 'github', url: 'https://github.com/manoj7894/swiggy-nodejs-devops-project.git'
+            }
+        }
+
+        stage('Install Package Dependencies') {
+            steps {
+                sh "npm install"
+            }
+        }
+
+        stage('Check for Tests') {
+            steps {
+                script {
+                    def testScriptExists = sh(script: "grep -q '\"test\":' package.json", returnStatus: true) == 0
+                    env.TEST_SCRIPT_EXISTS = testScriptExists ? 'true' : 'false'
+                }
+            }
+        }
+
+        stage('Trivy Filesystem Scan') {
+            steps {
+                sh "trivy fs --format table -o fs-report.html ."
+            }
+        }
+
+        // Optional: Uncomment if you want OWASP scanning
+        // stage('OWASP Scan') {
+        //     when {
+        //         expression {
+        //             fileExists('package.json')
+        //         }
+        //     }
+        //     steps {
+        //         dependencyCheck additionalArguments: '', odcInstallation: 'DP-Check'
+        //         dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
+        //     }
+        // }
+
+        stage('SonarQube') {
+            steps {
+                withSonarQubeEnv('Sonar_Install') {
+                    sh '''
+                        $SCANNER_HOME/bin/sonar-scanner \
+                        -Dsonar.projectName=Validate \
+                        -Dsonar.projectKey=Validate \
+                        -Dsonar.host.url=http://18.216.183.138:9000
+                    '''
+                }
+            }
+        }
+
+        stage('Stage V: QualityGates') {
+            steps {
+                echo "Running Quality Gates to verify the code quality"
+                script {
+                    timeout(time: 2, unit: 'MINUTES') {
+                        def qg = waitForQualityGate()
+                        if (qg.status != 'OK') {
+                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Build') {
+            steps {
+                script {
+                    withDockerRegistry(credentialsId: 'Docker_id', toolName: 'Docker') {
+                        sh "docker build -t ${DOCKER_IMAGE} ."
+                    }
+                }
+            }
+        }
+
+        stage('Trivy Image Scan') {
+            steps {
+                sh "trivy image ${DOCKER_IMAGE} > trivy.txt"
+            }
+        }
+
+        stage('Push') {
+            steps {
+                script {
+                    withDockerRegistry(credentialsId: 'Docker_id', toolName: 'Docker') {
+                        sh "docker push ${DOCKER_IMAGE}"
+                    }
+                }
+            }
+        }
+
+        stage('Update Deployment File') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
+                    script {
+                        sh '''
+                            git config user.email "jenkins@example.com"
+                            git config user.name "Jenkins"
+                        '''
+                        sh 'git checkout "${BRANCH}"'
+                        sh 'cat ${DEPLOYMENT_FILE_PATH}'
+                        sh '''
+                            sed -i "s|image: manoj3003/swigy:[^[:space:]]*|image: ${DOCKER_IMAGE}|g" ${DEPLOYMENT_FILE_PATH}
+                        '''
+                        sh '''
+                            if git diff --quiet; then
+                                echo "No changes detected in ${DEPLOYMENT_FILE_PATH}"
+                            else
+                                git add ${DEPLOYMENT_FILE_PATH}
+                                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                                git push -f https://${GIT_USER}:${GIT_TOKEN}@github.com/${GIT_USER}/${GIT_REPO_NAME}.git ${BRANCH}
+                            fi
+                        '''
+                    }
+                }
+            }
+        }
+
+        stage('Install Ingress Controller') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://893E5B8F2690F81B3FF2A73EE369E17B.yl4.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh '''
+                            if ! kubectl get namespace ingress-nginx; then
+                                kubectl create namespace ingress-nginx
+                            else
+                                echo "Namespace 'ingress-nginx' already exists."
+                            fi
+
+                            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml --namespace ingress-nginx
+                        '''
+                    }
+                }
+            }
+        }
+
+        stage('Install Calico Network Plugin') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://893E5B8F2690F81B3FF2A73EE369E17B.yl4.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh 'kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml'
+                    }
+                }
+            }
+        }
+
+        stage('Deploy to EKS') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://893E5B8F2690F81B3FF2A73EE369E17B.yl4.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh 'kubectl apply -f Kubernetes/pv.yml -n frissly'
+                        sh 'kubectl apply -f Kubernetes/pvc.yml -n frissly'
+                        sh 'kubectl apply -f ${DEPLOYMENT_FILE_PATH} -n frissly'
+                        sh 'kubectl apply -f Kubernetes/service.yml -n frissly'
+                        sh 'kubectl apply -f Kubernetes/autoscaling.yml -n frissly'
+                        sleep 20
+                    }
+                }
+            }
+        }
+
+        stage('Verify the Deployment') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://893E5B8F2690F81B3FF2A73EE369E17B.yl4.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh '''
+                            kubectl get pods -n frissly
+                            kubectl get svc -n frissly
+                            kubectl get pv -n frissly
+                            kubectl get pvc -n frissly
+                            kubectl get hpa -n frissly
+                        '''
+                    }
+                }
+            }
+        }
+    }
+
+    post {
+        always {
+            script {
+                def jobName = 'Frissly'
+                def buildNumber = env.BUILD_NUMBER
+                def pipelineStatus = currentBuild.result ?: 'SUCCESS'
+                def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'
+
+                def body = """<html>
+                                <body>
+                                    <div style="border: 4px solid ${bannerColor}; padding: 10px;">
+                                        <h2>${jobName} - Build ${buildNumber}</h2>
+                                        <div style="background-color: ${bannerColor}; padding: 10px;">
+                                            <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
+                                        </div>
+                                        <p>Check the <a href="${BUILD_URL}">console output</a>.</p> 
+                                    </div>
+                                </body>
+                            </html>"""
+
+                emailext(
+                    subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
+                    body: body,
+                    to: 'manojvarmapotthutri@gmail.com',
+                    from: 'jenkins@example.com',
+                    replyTo: 'jenkins@example.com',
+                    attachmentsPattern: 'trivy.txt, fs-report.html',
+                    mimeType: 'text/html'
+                )
+            }
+        }
+    }
+}
+
