Update Infrastructure-Setup

diff --git a/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup b/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup
--- a/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup
+++ b/Devops-Notes/Production-deployment-ways/Kubernetes/Infrastructure-Setup
@@ -1,7 +1,12 @@
 -> First We have to setup the Ec2, EKS, VPC infrastructure using terraform. The Script would be available this Github URL ()
--> We have to create Service Account and Roles in our EKS Cluster. The manifest files should be available in this Github URL ()
+-> We have to create Service Account and Roles in our EKS Cluster. Those manifest files should be available in this Github URL (https://github.com/manoj7894/Devops-AWS-2024/tree/master/Devops-Notes/Production-deployment-ways/Kubernetes/Service-Account-Files)
+
+# If you want to use docker private repo to store docker images in docker hub you should execute below command in server
+-> kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=manoj3003 --docker-password=Varma_3003 --namespace=frissly
+
+
 ->  After complete the infrastructure setup you will access Jenkins and sonarqube with the help of service public IP and those port numbers 
--> Loginto the Jenkins and Install below plugins
+-> Loginto the Jenkins and Go to manage Jenkins and click plugins Install below plugins
     -> Eclipse Temurin installer
     -> Docker
     -> Docker pipeline
@@ -24,11 +29,346 @@
 
 
 -> Go to manage Jenkins, click credentials and cofigure below credentials
-    docker -> Click username and password, Give username and password and give id name
-    Sonarube -> Click secret, Give token which you created in sonarqube and give id name
-    Git -> Click username and password, give username and token which you created in github, give id name
+    docker -> Click username and password, Give username and password and give id name  (Docker_id)
+    Sonarube -> Click secret text in kind, Give token which you created in sonarqube and give id name
+    Git -> Click username and password, give username and token which you created in github, give id name   (Bitbucket_user)
     Email -> Click username and password, Give mail-id and email token [To get this email-token you have to go gmail, click manage google account
                   click security and search App password in search bar and click app password and give one name and create
-    kuubernets-> Click secret text in kind and paste token which you copied eariler and id name and create     [You will get this token from Serviceaccount secret]
+    kuubernets-> Click secret text in kind and paste token which you copied eariler and id name and create     [You will get this token from Serviceaccount secret] (k8s_token)
 
+
+-> Go to manage Jenkins, click configuration tools and install below tools
+   JDK-17, Click automatically install, Click Install from adoptium.net and choose latest version
+   JDK-11, Click automatically install, Click Install from adoptium.net and choose latest version
+   Git, Keep it default
+   Sonar-scanner, Click install automatically, Choose latest version   (sonar-scanner)
+   Nodejs, Give name, Click install automatically    (node22)
+   Dependency check click install automatically and click Install from github.com and choose latest version    (DP-Check)
+   Maven, Give name, Click install automatically and choose latest version 
+   Docker, Give name Click install automatically and choose latest version    (Docker)
+
+
+
+-> Go to manage Jenkins, click the system configuration
+   SonarQube-Installition, Give name, Give the Sonar-qube URL and choose the soanr-token credentials id which you have created in credentials    (Sonar_Install)
+   Extended Email Notification -> Give smtp.gmail.com, Give 465 port, Click Advanced choose mail-id which you created in credentals, Click use SSL
+   Email Notification -> Give smtp.gmail.com, click advanced, click Use SMTP Authentication Give mail and email token which you created before in gmail, Click use SSL, Give 465 port
+
+
+-> To set up the sonar-quality gate. Go to sonarqube, click administation, click configuration, click webhook and give jenkins URL as like below
+       http://54.198.209.63:8080/sonarqube-webhook
+
+
+
+pipeline {
+    agent any
+
+    tools {
+        nodejs 'node22'
+    }
+
+    environment {
+        DOCKER_IMAGE = "manoj3003/frissly-k8s-images:${BUILD_NUMBER}"
+        BIT_REPO_NAME = "frissly-backend"
+        BIT_USERNAME = "manoj7894"
+        BRANCH = "kubernetes"
+        DEPLOYMENT_FILE_PATH = "Kubernetes/deployment.yml"
+        SCANNER_HOME = tool 'sonar-scanner'
+    }
+
+    stages {
+
+        stage('Cleanup Workspace') {
+            steps {
+                script {
+                    echo "Cleaning up the workspace..."
+                    cleanWs() // This cleans up the entire workspace directory.
+                }
+            }
+        }
+
+        stage('Remove All Previous Docker Images and Containers') {
+            steps {
+
+                // Remove all Docker images
+                sh 'docker rmi -f $(docker images -a -q) || true'
+                
+                // Clean up Docker volumes
+                sh 'docker volume prune -f || true'
+
+                // Clean up Docker build cache
+                sh 'docker builder prune -f || true'
+                
+                // Clean up unused networks
+                sh 'docker network prune -f || true'
+            }
+        }
+
+        stage('Cleanup Old Trivy Reports') {
+            steps {
+                script {
+                    echo "Cleaning up old Trivy reports..."
+                    sh '''
+                        rm -f trivy.txt
+                        rm -f fs-report.html
+                    '''
+                }
+            }
+        }
+
+        stage('Get Code') {
+            steps {
+                git branch: "${BRANCH}", credentialsId: 'Bitbucket_user', url: 'https://manoj7894@bitbucket.org/manojvarmapotthuri/frissly-backend.git'
+            }
+        }
+
+        stage('Install Package Dependencies') {
+            steps {
+                sh "npm install"
+            }
+        }
+
+        stage('Check for Tests') {
+            steps {
+                script {
+                    def testScriptExists = sh(script: "grep -q '\"test\":' package.json", returnStatus: true) == 0
+                    env.TEST_SCRIPT_EXISTS = testScriptExists ? 'true' : 'false'
+                }
+            }
+        }
+
+        stage('Trivy Filesystem Scan') {
+            steps {
+                script {
+                    sh "trivy fs --format table -o fs-report.html ."
+                }
+            }
+        }
+
+        // stage('OWASP Scan') {
+        //     when {
+        //         expression {
+        //             fileExists('package.json')
+        //         }
+        //     }
+        //     steps {
+        //         dependencyCheck additionalArguments: '', odcInstallation: 'DP-Check'
+        //         dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
+        //     }
+        // }
+
+        stage('SonarQube') {
+            steps {
+                withSonarQubeEnv('Sonar_Install') {
+                    sh '''
+                        $SCANNER_HOME/bin/sonar-scanner \
+                        -Dsonar.projectName=Validate \
+                        -Dsonar.projectKey=Validate \
+                        -Dsonar.host.url=http://3.147.61.213:9000
+                    '''
+                }
+            }
+        }
+
+        stage('Stage V: QualityGates') {
+            steps {
+                echo "Running Quality Gates to verify the code quality"
+                script {
+                    timeout(time: 2, unit: 'MINUTES') {
+                        def qg = waitForQualityGate()
+                        if (qg.status != 'OK') {
+                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Build') {
+            steps {
+                script {
+                    withDockerRegistry(credentialsId: 'Docker_id', toolName: 'Docker') {
+                        sh "docker build -t ${DOCKER_IMAGE} ."
+                    }
+                }
+            }
+        }
+
+        stage('Trivy Image Scan') {
+            steps {
+                script {
+                    sh "trivy image ${DOCKER_IMAGE} > trivy.txt"
+                }
+            }
+        }
+
+        stage('Push') {
+            steps {
+                script {
+                    withDockerRegistry(credentialsId: 'Docker_id', toolName: 'Docker') {
+                        sh "docker push ${DOCKER_IMAGE}"
+                    }
+                }
+            }
+        }
+
+        stage('Update Deployment File') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'Bitbucket_user', usernameVariable: 'BIT_USERNAME', passwordVariable: 'BIT_PASSWORD')]) {
+                    script {
+                        sh '''
+                            git config user.email "jenkins@example.com"
+                            git config user.name "Jenkins"
+                        '''
+
+                        sh 'git checkout "${BRANCH}"'
+                        sh 'cat ${DEPLOYMENT_FILE_PATH}'
+
+                        sh '''
+                            sed -i "s|image: manoj3003/frissly-k8s-images:[^[:space:]]*|image: ${DOCKER_IMAGE}|g" ${DEPLOYMENT_FILE_PATH}
+                        '''
+
+                        sh '''
+                            if git diff --quiet; then
+                                echo "No changes detected in ${DEPLOYMENT_FILE_PATH}"
+                            else
+                                git add ${DEPLOYMENT_FILE_PATH}
+                                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                                git push -f https://$BIT_USERNAME:$BIT_PASSWORD@bitbucket.org/manojvarmapotthuri/frissly-backend.git ${BRANCH}
+                            fi
+                        '''
+                    }
+                }
+            }
+        }
+
+        stage('Install Ingress Controller') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://BE39E8F32738D1A0762681AC6A754500.gr7.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh '''
+                            if ! kubectl get namespace ingress-nginx; then
+                                kubectl create namespace ingress-nginx
+                            else
+                                echo "Namespace 'ingress-nginx' already exists."
+                            fi
+
+                            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml --namespace ingress-nginx
+                        '''
+                    }
+                }
+            }
+        }
+
+        stage('Install Calico Network Plugin') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://BE39E8F32738D1A0762681AC6A754500.gr7.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh '''
+                            kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
+                        '''
+                    }
+                }
+            }
+        }
+        
+        stage('Deploy to EKS') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://BE39E8F32738D1A0762681AC6A754500.gr7.us-east-2.eks.amazonaws.com'
+                    ) {
+                        // Now apply the deployment and service in the webapps namespace
+                        sh 'kubectl apply -f Kubernetes/pv.yml -n frissly'
+                        sh 'kubectl apply -f Kubernetes/pvc.yml -n frissly'
+                        sh 'kubectl apply -f ${DEPLOYMENT_FILE_PATH} -n frissly'
+                        sh 'kubectl apply -f Kubernetes/service.yml -n frissly'
+                        sh 'kubectl apply -f Kubernetes/autoscaling.yml -n frissly'
+                        sleep 20
+                    }
+                }
+            }
+        }
+
+        stage('Verify the Deployment') {
+            steps {
+                script {
+                    withKubeConfig(
+                        caCertificate: '',
+                        clusterName: 'eks-1',
+                        contextName: '',
+                        credentialsId: 'k8s_token',
+                        namespace: 'frissly',
+                        restrictKubeConfigAccess: false,
+                        serverUrl: 'https://BE39E8F32738D1A0762681AC6A754500.gr7.us-east-2.eks.amazonaws.com'
+                    ) {
+                        sh '''
+                            kubectl get pods -n frissly
+                            kubectl get svc -n frissly
+                            kubectl get pv -n frissly
+                            kubectl get pvc -n frissly
+                            kubectl get hpa -n frissly
+                        '''
+                    }
+                }
+            }
+        }
+    }
+
+    post {
+        always {
+            script {
+                def jobName = 'Frissly'
+                def buildNumber = env.BUILD_NUMBER
+                def pipelineStatus = currentBuild.result ?: 'UNKNOWN'
+                def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'
+
+                def body = """<html>
+                                <body>
+                                    <div style="border: 4px solid ${bannerColor}; padding: 10px;">
+                                        <h2>${jobName} - Build ${buildNumber}</h2>
+                                        <div style="background-color: ${bannerColor}; padding: 10px;">
+                                            <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
+                                        </div>
+                                        <p>Check the <a href="${BUILD_URL}">console output</a>.</p> 
+                                    </div>
+                                </body>
+                            </html>"""
+
+                emailext(
+                    subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
+                    body: body,
+                    to: 'manojvarmapotthutri@gmail.com',
+                    from: 'jenkins@example.com',
+                    replyTo: 'jenkins@example.com',
+                    attachmentsPattern: 'trivy.txt',
+                    mimeType: 'text/html',
+                    attachmentPattern: 'fs-report.html'
+                )
+            }
+        }
+    }
+}
 
